[id]
deployer = "ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM"
faucet = "ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM"

[accounts.deployer]
mnemonic = "twice particular affair smile push picture miss direct tuna life side recipe group wisdom describe unable coral fortune attend detect convince physical amused bronze"
balance = 100_000_000_000_000

[accounts.wallet_1]
mnemonic = "sell invite acquire kitten bamboo drastic jelly vivid peace spawn twice guilt pave pen match myself hunt unlock cycle baby rhythm dust season match"
balance = 100_000_000_000_000

[accounts.wallet_2]
mnemonic = "hold excess usual noise coconut airline price together lyrics alien faculty milk when clarify disease captain calm gesture recipe have project problem point primary"
balance = 100_000_000_000_000

[accounts.wallet_3]
mnemonic = "cycle puppy glare enroll cost improve round trend wrist mushroom scorpion tower claim oppose clever elephant dinosaur eight problem before frozen dune wagon high"
balance = 100_000_000_000_000

[devnet]
disable_stacks_explorer = true
disable_stacks_api = true
